services:
  - type: web
    name: lakshmi-crackers-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --no-input && python manage.py collectstatic --no-input
    startCommand: gunicorn lakshmi_crackers.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        sync: false        # Set this in Render dashboard
      - key: POSTGRES_DB
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_PORT
        value: "5432"
